name: build tree-sitter
on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip3 install tree_sitter setuptools

      - name: Build tree-sitter
        run: python3 main.py

      - name: Upload tree-sitter
        uses: actions/upload-artifact@v4
        with:
          name: languages-linux.so
          path: build/languages.so

  build-macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip3 install tree_sitter setuptools

      - name: Build tree-sitter
        run: python3 main.py

      - name: Upload tree-sitter
        uses: actions/upload-artifact@v4
        with:
          name: languages-macos.so
          path: build/languages.so
